name: the_meal_db_api_client
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.0

dependencies:
  equatable: ^2.0.3
  http: ^0.13.5
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.8
  coverage: ^1.1.0
  json_serializable: ^6.1.5
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
