# name: mealify

# on:
#   pull_request:
#     paths:
#       - "lib/**"
#       - "test/**"
#       - "packages/**"
#       - "pubspec.yaml"
#       - ".github/workflows/mealify.yaml"
#   push:
#     branches:
#       - main
#     paths:
#       - "lib/**"
#       - "test/**"
#       - "packages/**"
#       - "pubspec.yaml"
#       - ".github/workflows/mealify.yaml"

# jobs:
#   build:
#     uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
#     with:
#       flutter_channel: stable
#       flutter_version: 3.7.0
