name: mealify

on:
  pull_request:
    paths:
      - "lib/**"
      - "test/**"
      - "packages/**"
      - "pubspec.yaml"
      - ".github/workflows/mealify.yaml"
  push:
    branches:
      - main
    paths:
      - "lib/**"
      - "test/**"
      - "packages/**"
      - "pubspec.yaml"
      - ".github/workflows/mealify.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build 🤖
        uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
